//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCamWindowsClient.WebCamService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebCamService.IWebCamService")]
    public interface IWebCamService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebCamService/getWebCamImage", ReplyAction="http://tempuri.org/IWebCamService/getWebCamImageResponse")]
        System.IO.Stream getWebCamImage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebCamService/Record", ReplyAction="http://tempuri.org/IWebCamService/RecordResponse")]
        void Record();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebCamServiceChannel : WebCamWindowsClient.WebCamService.IWebCamService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebCamServiceClient : System.ServiceModel.ClientBase<WebCamWindowsClient.WebCamService.IWebCamService>, WebCamWindowsClient.WebCamService.IWebCamService {
        
        public WebCamServiceClient() {
        }
        
        public WebCamServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebCamServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebCamServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebCamServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream getWebCamImage() {
            return base.Channel.getWebCamImage();
        }
        
        public void Record() {
            base.Channel.Record();
        }
    }
}
